version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./SignalRChat/SignalRChat.csproj --verbosity m
build_script:
  # ouput will be in ./*/bin/debug/netcoreapp2.1/publish
  - cmd: dotnet publish ./SignalRChat/SignalRChat.csproj
after_build:
  # For once the build has completed
artifacts:
  - path: '\SignalRChat\bin\Debug\netcoreapp2.1\publish'
    name: SignalRChatApp
    type: WebDeployPackage

clone_depth: 1

on_finish: 
  # any cleanup in here

deploy: off

build:
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - timothy.macharia@outlook.com
  subject: AppVeyor CI
  message: >-
    Continous Build


    Project Name: signalr_chat_aspnetcore2.1
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true