version: 1.0.{build}
build:
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - timothy.macharia@outlook.com
  subject: AppVeyor CI
  message: >-
    Continous Build


    Project Name: signalr_chat_aspnetcore2.1
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true